"""add_epic_fields_for_sprint3

Revision ID: 089aee7d2625
Revises: 0a2dbc99cd51
Create Date: 2026-04-23 09:06:00.459394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '089aee7d2625'
down_revision: Union[str, None] = '0a2dbc99cd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
