"""Add index to ticket priority and order_index

Revision ID: 3eddc7d254c0
Revises: add_blocked_support_v2
Create Date: 2026-06-12 01:36:54.370844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3eddc7d254c0'
down_revision: Union[str, None] = 'add_blocked_support_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tickets_order_index'), 'tickets', ['order_index'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_order_index'), table_name='tickets')
    # ### end Alembic commands ###
