"""fix_missing_ticket_columns

Revision ID: 5bf0e186bce7
Revises: 089aee7d2625
Create Date: 2026-05-08 04:08:04.324082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '5bf0e186bce7'
down_revision: Union[str, None] = '089aee7d2625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('block_reason', sa.String(length=1000), nullable=True))
    # Add as nullable first to avoid NotNullViolation on existing rows
    op.add_column('tickets', sa.Column('estimated_time_seconds', sa.Integer(), nullable=True))
    op.execute("UPDATE tickets SET estimated_time_seconds = 0 WHERE estimated_time_seconds IS NULL")
    op.alter_column('tickets', 'estimated_time_seconds', nullable=False)
    op.add_column('tickets', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'completed_at')
    op.drop_column('tickets', 'estimated_time_seconds')
    op.drop_column('tickets', 'block_reason')
    # ### end Alembic commands ###
