"""add_blocked_question_and_blocked_at_columns

Revision ID: add_blocked_support_v2
Revises: 5bf0e186bce7
Create Date: 2026-06-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_blocked_support_v2'
down_revision: Union[str, None] = 'h4i5j6k7l8m9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use IF NOT EXISTS to avoid failure when columns already exist
    op.execute("ALTER TABLE tickets ADD COLUMN IF NOT EXISTS blocked_question VARCHAR(1000)")
    op.execute("ALTER TABLE tickets ADD COLUMN IF NOT EXISTS blocked_at TIMESTAMP WITH TIME ZONE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'blocked_at')
    op.drop_column('tickets', 'blocked_question')
    # ### end Alembic commands ###
