"""Add Incident and Meeting models

Revision ID: e8395d114663
Revises: b5c6d7e8f9a0
Create Date: 2026-07-22 20:16:58.088033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e8395d114663'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', name='incident_status_enum'), nullable=False),
    sa.Column('severity', sa.Enum('P1', 'P2', 'P3', name='incident_severity_enum'), nullable=False),
    sa.Column('affected_environment', sa.Enum('PRODUCTION', 'STAGING', 'DEV', name='incident_environment_enum'), nullable=False),
    sa.Column('estimated_resolution_time_seconds', sa.Integer(), nullable=False),
    sa.Column('mitigation_state', sa.Text(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_affected_environment'), 'incidents', ['affected_environment'], unique=False)
    op.create_index(op.f('ix_incidents_application_id'), 'incidents', ['application_id'], unique=False)
    op.create_index(op.f('ix_incidents_assigned_to_id'), 'incidents', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_created_by_id'), 'incidents', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('meetings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.Enum('DAILY', 'PLANNING', 'RETROSPECTIVE', 'OTHER', name='meeting_type_enum'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_markdown', sa.Text(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_application_id'), 'meetings', ['application_id'], unique=False)
    op.create_index(op.f('ix_meetings_created_at'), 'meetings', ['created_at'], unique=False)
    op.create_index(op.f('ix_meetings_created_by_id'), 'meetings', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_type'), 'meetings', ['meeting_type'], unique=False)
    op.create_table('meeting_attendances',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'JUSTIFIED', name='attendance_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_attendances_created_at'), 'meeting_attendances', ['created_at'], unique=False)
    op.create_index(op.f('ix_meeting_attendances_meeting_id'), 'meeting_attendances', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendances_user_id'), 'meeting_attendances', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tickets_epic_id_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_epic_status_duedate'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status_notcompleted_duedate'), table_name='tickets', postgresql_where="(status <> 'COMPLETED'::ticket_status_enum)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tickets_status_notcompleted_duedate'), 'tickets', ['status', 'due_date'], unique=False, postgresql_where="(status <> 'COMPLETED'::ticket_status_enum)")
    op.create_index(op.f('ix_tickets_epic_status_duedate'), 'tickets', ['epic_id', 'status', 'due_date'], unique=False)
    op.create_index(op.f('ix_tickets_epic_id_status'), 'tickets', ['epic_id', 'status'], unique=False)
    op.drop_index(op.f('ix_meeting_attendances_user_id'), table_name='meeting_attendances')
    op.drop_index(op.f('ix_meeting_attendances_meeting_id'), table_name='meeting_attendances')
    op.drop_index(op.f('ix_meeting_attendances_created_at'), table_name='meeting_attendances')
    op.drop_table('meeting_attendances')
    op.drop_index(op.f('ix_meetings_meeting_type'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_by_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_application_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_by_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_to_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_application_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_affected_environment'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
